// ---------------------------------------------------------------------------
// GardenOS – Built-in Plant Species Database (Danish garden plants)
// ---------------------------------------------------------------------------
// MVP: name, category, spacing, light, water, companions, family, icon
// All data verified for Danish growing conditions (zone 7–8).
// ---------------------------------------------------------------------------

import type { PlantSpecies } from "./plantTypes";

export const BUILTIN_PLANTS: PlantSpecies[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // GRØNTSAGER – Rodfrugter
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "gulerod",
    name: "Gulerod",
    latinName: "Daucus carota",
    category: "vegetable",
    subCategory: "root",
    family: "apiaceae",
    lifecycle: "biennial",
    sowOutdoor: { from: 3, to: 6 },
    harvest: { from: 6, to: 10 },
    spacingCm: 5,
    rowSpacingCm: 25,
    rootDepthCm: 30,
    light: "full-sun",
    water: "medium",
    soil: ["sandy", "loamy"],
    goodCompanions: ["loeg", "purloeg", "tomat", "aert", "salat"],
    badCompanions: ["dild", "pastinak"],
    rotationYears: 3,
    icon: "🥕",
    difficulty: "easy",
    taste: "Sød og sprød rå, blødere og mere aromatisk kogt. Sødme stiger efter frost.",
    culinaryUses: "Rå i salat, suppe, juice, stegt som tilbehør, gulerodskage, babymad. Passer til ingefær, spidskommen, honning.",
    harvestTips: "Træk op når toppen er 1-2 cm i diameter. Tidlige sorter efter 10-12 uger, sene sorter kan stå til frost som giver mere sødme.",
    soilAmendments: "Løs dyb jord uden sten giver de flotteste rødder. Undgå frisk gødning (giver forgrenede rødder).",
    fertilizerInfo: "Lav næring — for meget kvælstof giver topvækst frem for rødder. Evt. kalium-gødning i juni.",
    pests: ["Gulerodsflue", "Bladlopper"],
    diseases: ["Gulerodsskimmel", "Sortråd"],
    storageInfo: "Holdes i fugtig sand i kælder (0-2°C) i flere måneder. Kan også fryses blanchard.",
    nutrition: { kcal: 41, proteinG: 0.9, fatG: 0.2, carbG: 10, fiberG: 2.8, highlights: "Rig på beta-caroten (A-vitamin), kalium og antioxidanter." },
    varieties: [
      { id: "nantes", name: "Nantes 2", description: "Klassisk dansk sort, cylindrisk, sød og sprød. Perfekt til frisk spisning.", daysToHarvest: 100, taste: "Meget sød og saftig", color: "orange", storageQuality: "good" },
      { id: "autumn-king", name: "Autumn King", description: "Sen sort med store, koniske rødder. God til vinteropbevaring.", daysToHarvest: 130, taste: "Sød, tæt kød", color: "mørk orange", storageQuality: "excellent" },
      { id: "rodelika", name: "Rodelika", description: "Biodynamisk favori med dyb farve og fin smag.", daysToHarvest: 110, taste: "Fyldig, sød", color: "dyb orange", storageQuality: "good" },
      { id: "paris-market", name: "Parisisk Marked", description: "Runde, små gulerødder — perfekt til tung jord og krukker.", daysToHarvest: 70, spacingCm: 3, taste: "Sød, mild", color: "orange", storageQuality: "fair" },
      { id: "purple-haze", name: "Purple Haze", description: "Lilla udenpå, orange indeni. Dekorativ og lækker.", daysToHarvest: 110, taste: "Sød med krydret dybde", color: "lilla/orange", storageQuality: "fair" },
      { id: "flyaway", name: "Flyaway", description: "Resistent mod gulerodsflue — perfekt til økologisk dyrkning.", daysToHarvest: 100, taste: "Sød, sprød", color: "orange", resistances: ["gulerodsflue"], storageQuality: "good" },
    ],
    forestGardenLayer: "root",
    source: "builtin",
  },
  {
    id: "pastinak",
    name: "Pastinak",
    latinName: "Pastinaca sativa",
    category: "vegetable",
    subCategory: "root",
    family: "apiaceae",
    lifecycle: "biennial",
    sowOutdoor: { from: 3, to: 5 },
    harvest: { from: 9, to: 12 },
    spacingCm: 15,
    rowSpacingCm: 30,
    rootDepthCm: 40,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "sandy"],
    goodCompanions: ["loeg", "hvidloeg"],
    badCompanions: ["gulerod", "dild"],
    rotationYears: 3,
    icon: "🥕",
    nutrition: { kcal: 75, proteinG: 1.2, fatG: 0.3, carbG: 18, fiberG: 4.9, highlights: "Rig på kostfibre, kalium, C-vitamin og folat." },
    forestGardenLayer: "root",
    source: "builtin",
  },
  {
    id: "roedbed",
    name: "Rødbede",
    latinName: "Beta vulgaris",
    category: "vegetable",
    subCategory: "root",
    family: "other",
    lifecycle: "biennial",
    sowOutdoor: { from: 4, to: 6 },
    harvest: { from: 7, to: 10 },
    spacingCm: 10,
    rowSpacingCm: 30,
    rootDepthCm: 20,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["loeg", "hvidloeg", "salat", "kaalrabi"],
    badCompanions: ["spinat"],
    rotationYears: 3,
    icon: "🟣",
    nutrition: { kcal: 43, proteinG: 1.6, fatG: 0.2, carbG: 10, fiberG: 2.8, highlights: "Nitrat (blodtryksænkende), folat, mangan og antioxidanter (betalainer)." },
    forestGardenLayer: "root",
    source: "builtin",
  },
  {
    id: "radise",
    name: "Radise",
    latinName: "Raphanus sativus",
    category: "vegetable",
    subCategory: "root",
    family: "brassicaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 3, to: 8 },
    harvest: { from: 4, to: 9 },
    spacingCm: 3,
    rowSpacingCm: 15,
    rootDepthCm: 10,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "sandy"],
    goodCompanions: ["aert", "salat", "tomat", "spinat"],
    badCompanions: ["agurk"],
    rotationYears: 2,
    icon: "🔴",
    nutrition: { kcal: 16, proteinG: 0.7, fatG: 0.1, carbG: 3.4, fiberG: 1.6, highlights: "C-vitamin, folat og isothiocyanater (kræftforebyggende)." },
    forestGardenLayer: "root",
    source: "builtin",
  },
  {
    id: "kartoffel",
    name: "Kartoffel",
    latinName: "Solanum tuberosum",
    category: "vegetable",
    subCategory: "root",
    family: "solanaceae",
    lifecycle: "annual",
    plantOut: { from: 4, to: 5 },
    harvest: { from: 7, to: 9 },
    spacingCm: 35,
    rowSpacingCm: 60,
    rootDepthCm: 30,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "sandy"],
    goodCompanions: ["boenner", "aert", "spinat", "salat"],
    badCompanions: ["tomat", "agurk", "graeskar", "solbaer"],
    rotationYears: 4,
    icon: "🥔",
    difficulty: "easy",
    taste: "Stivelsesrig, mild-nøddet. Smag og konsistens varierer meget mellem sorter (fast, melede, vokset).",
    culinaryUses: "Kogt, bagt, stegt, mos, pommes frites, kartoffelsalat, gratin, gnocchi. Nye kartofler med smør og persille!",
    harvestTips: "Tidlige: høst når blomsten visner (juni-juli). Sene: vent til toppen er helt visnet. Grav forsigtigt med greb.",
    soilAmendments: "Løs, let sur jord (pH 5.5-6.5). Undgå kalk — fremmer skurv. Bland kompost i året før.",
    fertilizerInfo: "Moderat: kompost ved plantning + evt. kaliumrig gødning ved hypning. Ikke for meget kvælstof.",
    pests: ["Kartoffelskimmel", "Bladlus", "Kartoffelcystenematod", "Coloradobille (sjælden i DK)"],
    diseases: ["Kartoffelskimmel (Phytophthora)", "Kartoffelskurv", "Sortben"],
    storageInfo: "Mørkt, køligt (4-8°C), ventileret. Aldrig i plastik. Holder 3-6 mdr. afhængig af sort.",
    nutrition: { kcal: 77, proteinG: 2.0, fatG: 0.1, carbG: 17, fiberG: 2.2, highlights: "God kilde til C-vitamin, kalium, B6 og kostfibre (med skræl)." },
    varieties: [
      { id: "anya", name: "Anya", description: "Fingerling-type med fin smag. Fantastisk i kartoffelsalat.", daysToHarvest: 110, taste: "Nøddet, fast kød", color: "lyserød skræl", storageQuality: "good" },
      { id: "bintje", name: "Bintje", description: "Klassisk dansk lagersort, god alsidig kartoffel.", daysToHarvest: 130, taste: "Melet, mild", color: "gul", storageQuality: "excellent" },
      { id: "asparges", name: "Asparges", description: "Dansk specialitet, lang fingerkartoffel med fantastisk smag.", daysToHarvest: 120, taste: "Nøddet, vokset", color: "gul", storageQuality: "good" },
      { id: "berber", name: "Berber", description: "Tidlig sort, fin til nye kartofler. Lav modstandsdygtighed mod skimmel.", daysToHarvest: 70, taste: "Frisk, mild", color: "gul", storageQuality: "poor" },
      { id: "king-edward", name: "King Edward", description: "Engelsk klassiker, perfekt til bagt kartoffel og mos.", daysToHarvest: 130, taste: "Melet, blød", color: "hvid/lyserød", storageQuality: "excellent" },
      { id: "blaa-congo", name: "Blå Congo", description: "Lilla helt igennem! Dekorativ og smagfuld.", daysToHarvest: 120, taste: "Nøddet, fast", color: "mørk lilla", storageQuality: "good" },
    ],
    forestGardenLayer: "root",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRØNTSAGER – Kål
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "broccoli",
    name: "Broccoli",
    latinName: "Brassica oleracea var. italica",
    category: "vegetable",
    subCategory: "brassica",
    family: "brassicaceae",
    lifecycle: "annual",
    sowIndoor: { from: 3, to: 4 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 7, to: 10 },
    spacingCm: 45,
    rowSpacingCm: 60,
    rootDepthCm: 45,
    light: "full-sun",
    water: "high",
    soil: ["loamy", "clay"],
    goodCompanions: ["dild", "rosmarin", "salat", "loeg"],
    badCompanions: ["tomat", "jordbeer"],
    rotationYears: 3,
    icon: "🥦",
    nutrition: { kcal: 34, proteinG: 2.8, fatG: 0.4, carbG: 7, fiberG: 2.6, highlights: "Sulforaphan, C-vitamin, K-vitamin, folat og jern." },
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "hvidkaal",
    name: "Hvidkål",
    latinName: "Brassica oleracea var. capitata",
    category: "vegetable",
    subCategory: "brassica",
    family: "brassicaceae",
    lifecycle: "annual",
    sowIndoor: { from: 2, to: 4 },
    plantOut: { from: 4, to: 6 },
    harvest: { from: 7, to: 11 },
    spacingCm: 50,
    rowSpacingCm: 60,
    rootDepthCm: 45,
    light: "full-sun",
    water: "high",
    soil: ["loamy", "clay"],
    goodCompanions: ["dild", "selleri", "roedbed", "loeg"],
    badCompanions: ["tomat", "jordbeer"],
    rotationYears: 3,
    icon: "🥬",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "groenkaal",
    name: "Grønkål",
    latinName: "Brassica oleracea var. sabellica",
    category: "vegetable",
    subCategory: "brassica",
    family: "brassicaceae",
    lifecycle: "biennial",
    sowIndoor: { from: 3, to: 5 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 9, to: 2 },
    spacingCm: 50,
    rowSpacingCm: 60,
    rootDepthCm: 45,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    frostHardy: true,
    goodCompanions: ["dild", "rosmarin", "kartoffel"],
    badCompanions: ["jordbeer", "tomat"],
    rotationYears: 3,
    icon: "🥬",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "kaalrabi",
    name: "Kålrabi",
    latinName: "Brassica oleracea var. gongylodes",
    category: "vegetable",
    subCategory: "brassica",
    family: "brassicaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 4, to: 7 },
    harvest: { from: 6, to: 10 },
    spacingCm: 25,
    rowSpacingCm: 30,
    rootDepthCm: 20,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["salat", "loeg", "roedbed"],
    badCompanions: ["tomat", "jordbeer"],
    rotationYears: 3,
    icon: "🟢",
    nutrition: { kcal: 27, proteinG: 1.7, fatG: 0.1, carbG: 6, fiberG: 3.6, highlights: "C-vitamin, kalium og kostfibre. God både rå og kogt." },
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRØNTSAGER – Bælgfrugter
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "aert",
    name: "Ært",
    latinName: "Pisum sativum",
    category: "vegetable",
    subCategory: "legume",
    family: "fabaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 3, to: 6 },
    harvest: { from: 6, to: 8 },
    spacingCm: 5,
    rowSpacingCm: 40,
    rootDepthCm: 30,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "sandy"],
    goodCompanions: ["gulerod", "radise", "salat", "spinat", "agurk"],
    badCompanions: ["loeg", "hvidloeg", "purloeg"],
    rotationYears: 3,
    icon: "🫛",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "boenner",
    name: "Bønner (busk)",
    latinName: "Phaseolus vulgaris",
    category: "vegetable",
    subCategory: "legume",
    family: "fabaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 5, to: 6 },
    harvest: { from: 7, to: 9 },
    spacingCm: 15,
    rowSpacingCm: 40,
    rootDepthCm: 30,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    minTempC: 10,
    goodCompanions: ["gulerod", "agurk", "kartoffel", "selleri"],
    badCompanions: ["loeg", "hvidloeg", "fennikel"],
    rotationYears: 3,
    icon: "🫘",
    nutrition: { kcal: 31, proteinG: 1.8, fatG: 0.1, carbG: 7, fiberG: 3.4, highlights: "Protein, kostfibre, folat, C-vitamin og mangan." },
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "storboenne",
    name: "Storbønne / hestebønne",
    latinName: "Vicia faba",
    category: "vegetable",
    subCategory: "legume",
    family: "fabaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 3, to: 4 },
    harvest: { from: 7, to: 8 },
    spacingCm: 20,
    rowSpacingCm: 45,
    rootDepthCm: 30,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    frostHardy: true,
    goodCompanions: ["kartoffel", "spinat"],
    badCompanions: ["loeg", "hvidloeg"],
    rotationYears: 3,
    icon: "🫘",
    nutrition: { kcal: 88, proteinG: 7.6, fatG: 0.7, carbG: 18, fiberG: 5.4, highlights: "Højt protein, folat, mangan, jern og fosfor." },
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRØNTSAGER – Bladgrønt
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "salat",
    name: "Salat",
    latinName: "Lactuca sativa",
    category: "vegetable",
    subCategory: "leafy",
    family: "asteraceae",
    lifecycle: "annual",
    sowOutdoor: { from: 3, to: 8 },
    harvest: { from: 5, to: 10 },
    spacingCm: 25,
    rowSpacingCm: 30,
    rootDepthCm: 15,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy", "any"],
    goodCompanions: ["gulerod", "radise", "jordbeer", "loeg", "dild"],
    badCompanions: ["selleri"],
    rotationYears: 1,
    icon: "🥬",
    difficulty: "easy",
    taste: "Frisk, sprød, mild. Varierer fra blød smøragtig (hovedsalat) til bitter-nøddet (rucola) og knas (iceberg).",
    culinaryUses: "Frisk i salater, på sandwiches, wraps. Kan også grilles eller bruges i wok.",
    harvestTips: "Høst de yderste blade løbende (cut-and-come-again) eller hele hovedet. Morgenhøst giver sprødeste blade.",
    fertilizerInfo: "Let gødning — kompost ved såning. Undgå overgødning da det fremmer skydning.",
    pests: ["Snegle", "Bladlus"],
    diseases: ["Salatskimmel", "Gråskimmel"],
    storageInfo: "Kort holdbarhed (1-2 uger i køleskab). Vask først lige før brug.",
    nutrition: { kcal: 15, proteinG: 1.4, fatG: 0.2, carbG: 2.9, fiberG: 1.3, highlights: "Folat, K-vitamin, A-vitamin og vand (95 %). Meget lavt kalorieindhold." },
    varieties: [
      { id: "lollo-rossa", name: "Lollo Rossa", description: "Krøllet rødt blad, dekorativ og let bitter.", daysToHarvest: 55, taste: "Let bitter, sprød", color: "rød/grøn" },
      { id: "butterhead", name: "Smørsalat", description: "Klassisk dansk hovedsalat med bløde blade.", daysToHarvest: 60, taste: "Mild, smøragtig", color: "lysgrøn" },
      { id: "romaine", name: "Romaine / Cos", description: "Høj, sprød salat — den rigtige til Caesar-salat.", daysToHarvest: 65, taste: "Sprød, mild, let sød", color: "mørkgrøn" },
      { id: "egebladssalat", name: "Egebladssalat", description: "Fliget blad som egeblade, nøddet smag.", daysToHarvest: 50, taste: "Nøddet, mild", color: "grøn/rød" },
    ],
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "spinat",
    name: "Spinat",
    latinName: "Spinacia oleracea",
    category: "vegetable",
    subCategory: "leafy",
    family: "other",
    lifecycle: "annual",
    sowOutdoor: { from: 3, to: 5 },
    harvest: { from: 5, to: 7 },
    spacingCm: 15,
    rowSpacingCm: 25,
    rootDepthCm: 15,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["jordbeer", "radise", "aert", "boenner"],
    badCompanions: ["roedbed"],
    rotationYears: 2,
    icon: "🍃",
    nutrition: { kcal: 23, proteinG: 2.9, fatG: 0.4, carbG: 3.6, fiberG: 2.2, highlights: "Jern, calcium, K-vitamin, folat, magnesium og lutein." },
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "mangold",
    name: "Mangold / bladselleri",
    latinName: "Beta vulgaris subsp. vulgaris",
    category: "vegetable",
    subCategory: "leafy",
    family: "other",
    lifecycle: "biennial",
    sowOutdoor: { from: 4, to: 6 },
    harvest: { from: 6, to: 10 },
    spacingCm: 30,
    rowSpacingCm: 40,
    rootDepthCm: 20,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["boenner", "kaal", "loeg"],
    badCompanions: [],
    rotationYears: 2,
    icon: "🥬",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRØNTSAGER – Natskyggefamilien
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "tomat",
    name: "Tomat",
    latinName: "Solanum lycopersicum",
    category: "vegetable",
    subCategory: "nightshade",
    family: "solanaceae",
    lifecycle: "annual",
    sowIndoor: { from: 3, to: 4 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 7, to: 10 },
    spacingCm: 50,
    rowSpacingCm: 70,
    rootDepthCm: 50,
    light: "full-sun",
    water: "high",
    soil: ["loamy"],
    minTempC: 10,
    goodCompanions: ["basilikum", "gulerod", "persille", "purloeg"],
    badCompanions: ["kartoffel", "fennikel", "broccoli", "hvidkaal"],
    rotationYears: 3,
    icon: "🍅",
    difficulty: "medium",
    taste: "Sød-syrlig, kødfuld. Smagen varierer enormt mellem sorter — fra intens og kompleks til mild og saftig.",
    culinaryUses: "Frisk i salat, bruschetta, caprese. Kogt i sauce, suppe, chutney, salsa. Tørret, syltet, ovnbagt.",
    harvestTips: "Høst når frugten er jævnt farvet og giver lidt efter ved tryk. Grønne tomater kan eftermodnes indendørs.",
    soilAmendments: "Næringsrig jord med god dræning. Bland kompost og evt. nebryde-kalk ved plantning.",
    fertilizerInfo: "Stærkfoder: tomat-gødning (højt kalium) hver 2. uge fra blomstring. Undgå for meget kvælstof.",
    pests: ["Bladlus", "Tomatmøl (hvid sommerfugl)", "Snegle"],
    diseases: ["Kartoffelskimmel", "Gråskimmel", "Bladplet"],
    storageInfo: "Opbevar ALDRIG i køleskab (ødelægger smag). Stuetemperatur, stilkenden opad. Kan syltes eller fryses til sauce.",
    nutrition: { kcal: 18, proteinG: 0.9, fatG: 0.2, carbG: 3.9, fiberG: 1.2, highlights: "Rig på lycopen (antioxidant), C-vitamin og kalium." },
    varieties: [
      { id: "sungold", name: "Sungold F1", description: "Cocktailtomat, uovertruffent sød. Orange frugter i klaser.", daysToHarvest: 65, taste: "Meget sød, tropisk", color: "orange", storageQuality: "poor" },
      { id: "gardeners-delight", name: "Gardener's Delight", description: "Pålidelig cocktailtomat, klassisk sød-syrlig smag. Let at dyrke.", daysToHarvest: 70, taste: "Sød-syrlig, klassisk", color: "rød", storageQuality: "fair" },
      { id: "san-marzano", name: "San Marzano", description: "Italiensk flasketomat — den bedste til sauce og passata.", daysToHarvest: 85, taste: "Intens, kødfuld, lav syre", color: "rød", storageQuality: "good" },
      { id: "tigerella", name: "Tigerella", description: "Stribet røde/gule frugter med kraftig smag.", daysToHarvest: 75, taste: "Kompleks, tangy", color: "rød/gul stribet", storageQuality: "fair" },
      { id: "black-cherry", name: "Black Cherry", description: "Mørke kirsebærtomater med dyb, kompleks smag.", daysToHarvest: 75, taste: "Dyb, sød, rund", color: "mørk rød/brun", storageQuality: "poor" },
      { id: "moneymaker", name: "Moneymaker", description: "Pålidelig mellem-tomat til dansk klima. God alsidighed.", daysToHarvest: 80, taste: "Mild, balanceret", color: "rød", storageQuality: "fair" },
      { id: "costoluto", name: "Costoluto Fiorentino", description: "Italiensk bøftomat med ribbede frugter. Fantastisk smag.", daysToHarvest: 90, taste: "Intens, syrlig-sød", color: "dyb rød", storageQuality: "fair" },
    ],
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "peber",
    name: "Peberfrugt",
    latinName: "Capsicum annuum",
    category: "vegetable",
    subCategory: "nightshade",
    family: "solanaceae",
    lifecycle: "annual",
    sowIndoor: { from: 2, to: 3 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 7, to: 10 },
    spacingCm: 40,
    rowSpacingCm: 60,
    rootDepthCm: 40,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    minTempC: 15,
    goodCompanions: ["basilikum", "gulerod", "tomat"],
    badCompanions: ["kartoffel", "fennikel"],
    rotationYears: 3,
    icon: "🫑",
    nutrition: { kcal: 26, proteinG: 1.0, fatG: 0.3, carbG: 6, fiberG: 2.1, highlights: "Enorm C-vitamin (3× citron!), A-vitamin og antioxidanter." },
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "chili",
    name: "Chili",
    latinName: "Capsicum spp.",
    category: "vegetable",
    subCategory: "nightshade",
    family: "solanaceae",
    lifecycle: "annual",
    sowIndoor: { from: 1, to: 3 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 7, to: 10 },
    spacingCm: 40,
    rowSpacingCm: 50,
    rootDepthCm: 35,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    minTempC: 15,
    goodCompanions: ["basilikum", "tomat", "gulerod"],
    badCompanions: ["kartoffel", "fennikel"],
    rotationYears: 3,
    icon: "🌶️",
    nutrition: { kcal: 40, proteinG: 1.9, fatG: 0.4, carbG: 9, fiberG: 1.5, highlights: "Capsaicin (stofskiftefremmer), C-vitamin og A-vitamin." },
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRØNTSAGER – Græskarfamilien
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "agurk",
    name: "Agurk",
    latinName: "Cucumis sativus",
    category: "vegetable",
    subCategory: "cucurbit",
    family: "cucurbitaceae",
    lifecycle: "annual",
    sowIndoor: { from: 4, to: 5 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 7, to: 9 },
    spacingCm: 40,
    rowSpacingCm: 100,
    rootDepthCm: 30,
    light: "full-sun",
    water: "high",
    soil: ["loamy"],
    minTempC: 12,
    goodCompanions: ["aert", "boenner", "salat", "dild", "solsikke"],
    badCompanions: ["kartoffel", "radise"],
    rotationYears: 3,
    icon: "🥒",
    difficulty: "medium",
    taste: "Frisk, vandrig, let sød. Slangeagurker er milde, drueagurker mere intense, sylteagurker faste og sprøde.",
    culinaryUses: "Rå i salat, på rugbrød, tzatziki, pickles, agurkesalat med eddike, cold soup (gazpacho).",
    harvestTips: "Høst ofte — oversåede frugter bremser ny produktion. Slange: 20-30 cm. Sylte: 8-12 cm.",
    fertilizerInfo: "Næringsrig jord med masser af kompost. Flødende gødning hver uge under frugtdannelse.",
    pests: ["Bladlus", "Spindemider (i drivhus)", "Snegle"],
    diseases: ["Meldug", "Agurkmosaikvirus"],
    storageInfo: "Kort holdbarhed (1 uge i køleskab). Syltes/laves til pickles for længere holdbarhed.",
    nutrition: { kcal: 12, proteinG: 0.7, fatG: 0.1, carbG: 2.2, fiberG: 0.7, highlights: "Vand (96 %), K-vitamin, kalium. Meget lavt kalorieindhold, forfriskende." },
    varieties: [
      { id: "marketmore", name: "Marketmore 76", description: "Klassisk slangeagurk, pålidelig udendørs.", daysToHarvest: 65, taste: "Frisk, sprød", color: "mørkgrøn", resistances: ["meldug"] },
      { id: "diva", name: "Diva", description: "Tynd skræl, ingen bitterhed, selvbestøvende.", daysToHarvest: 58, taste: "Mild, sød", color: "grøn" },
      { id: "vorgebirgstrauben", name: "Vorgebirgstrauben", description: "Gammel tysk drueagurk-sort, mange små frugter.", daysToHarvest: 60, taste: "Intens, sprød", color: "lysegrøn" },
    ],
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "squash",
    name: "Squash / courgette",
    latinName: "Cucurbita pepo",
    category: "vegetable",
    subCategory: "cucurbit",
    family: "cucurbitaceae",
    lifecycle: "annual",
    sowIndoor: { from: 4, to: 5 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 7, to: 10 },
    spacingCm: 80,
    rowSpacingCm: 100,
    rootDepthCm: 30,
    light: "full-sun",
    water: "high",
    soil: ["loamy"],
    minTempC: 10,
    goodCompanions: ["boenner", "aert", "radise", "morgenfrue"],
    badCompanions: ["kartoffel"],
    rotationYears: 3,
    icon: "🟡",
    nutrition: { kcal: 17, proteinG: 1.2, fatG: 0.3, carbG: 3.1, fiberG: 1.0, highlights: "Lavt kalorieindhold, C-vitamin, kalium og mangan." },
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "graeskar",
    name: "Græskar",
    latinName: "Cucurbita maxima",
    category: "vegetable",
    subCategory: "cucurbit",
    family: "cucurbitaceae",
    lifecycle: "annual",
    sowIndoor: { from: 4, to: 5 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 9, to: 10 },
    spacingCm: 120,
    rowSpacingCm: 150,
    rootDepthCm: 40,
    light: "full-sun",
    water: "high",
    soil: ["loamy"],
    minTempC: 10,
    goodCompanions: ["boenner", "aert", "morgenfrue"],
    badCompanions: ["kartoffel"],
    rotationYears: 3,
    icon: "🎃",
    nutrition: { kcal: 26, proteinG: 1.0, fatG: 0.1, carbG: 7, fiberG: 0.5, highlights: "Beta-caroten (A-vitamin), C-vitamin og kalium. Kerner rige på zink." },
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRØNTSAGER – Løgfamilien
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "loeg",
    name: "Løg",
    latinName: "Allium cepa",
    category: "vegetable",
    subCategory: "allium",
    family: "amaryllidaceae",
    lifecycle: "biennial",
    sowOutdoor: { from: 3, to: 4 },
    harvest: { from: 7, to: 9 },
    spacingCm: 10,
    rowSpacingCm: 25,
    rootDepthCm: 15,
    light: "full-sun",
    water: "low",
    soil: ["loamy", "sandy"],
    goodCompanions: ["gulerod", "salat", "tomat", "jordbeer", "roedbed"],
    badCompanions: ["aert", "boenner"],
    rotationYears: 3,
    icon: "🧅",
    nutrition: { kcal: 40, proteinG: 1.1, fatG: 0.1, carbG: 9, fiberG: 1.7, highlights: "Quercetin (antioxidant), C-vitamin og præbiotiske fibre." },
    forestGardenLayer: "root",
    source: "builtin",
  },
  {
    id: "hvidloeg",
    name: "Hvidløg",
    latinName: "Allium sativum",
    category: "vegetable",
    subCategory: "allium",
    family: "amaryllidaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 11 },
    harvest: { from: 7, to: 8 },
    spacingCm: 15,
    rowSpacingCm: 25,
    rootDepthCm: 15,
    light: "full-sun",
    water: "low",
    soil: ["loamy", "sandy"],
    goodCompanions: ["gulerod", "tomat", "jordbeer", "roedbed"],
    badCompanions: ["aert", "boenner"],
    rotationYears: 3,
    icon: "🧄",
    nutrition: { kcal: 149, proteinG: 6.4, fatG: 0.5, carbG: 33, fiberG: 2.1, highlights: "Allicin (antibakterielt), mangan, B6-vitamin og selen." },
    forestGardenLayer: "root",
    source: "builtin",
  },
  {
    id: "purloeg",
    name: "Purløg",
    latinName: "Allium schoenoprasum",
    category: "herb",
    family: "amaryllidaceae",
    lifecycle: "perennial",
    sowOutdoor: { from: 3, to: 5 },
    harvest: { from: 4, to: 10 },
    spacingCm: 15,
    rowSpacingCm: 25,
    rootDepthCm: 15,
    light: "full-sun",
    water: "low",
    soil: ["any"],
    goodCompanions: ["gulerod", "tomat", "jordbeer"],
    badCompanions: ["aert", "boenner"],
    rotationYears: 0,
    icon: "🌿",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "porre",
    name: "Porre",
    latinName: "Allium porrum",
    category: "vegetable",
    subCategory: "allium",
    family: "amaryllidaceae",
    lifecycle: "biennial",
    sowIndoor: { from: 2, to: 3 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 9, to: 12 },
    spacingCm: 15,
    rowSpacingCm: 30,
    rootDepthCm: 20,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["gulerod", "selleri", "salat"],
    badCompanions: ["aert", "boenner"],
    rotationYears: 3,
    icon: "🥬",
    nutrition: { kcal: 61, proteinG: 1.5, fatG: 0.3, carbG: 14, fiberG: 1.8, highlights: "K-vitamin, folat, mangan og præbiotiske fibre (inulin)." },
    forestGardenLayer: "root",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRØNTSAGER – Skærmplantefamilien
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "selleri",
    name: "Bladselleri",
    latinName: "Apium graveolens",
    category: "vegetable",
    subCategory: "other",
    family: "apiaceae",
    lifecycle: "biennial",
    sowIndoor: { from: 2, to: 3 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 8, to: 10 },
    spacingCm: 25,
    rowSpacingCm: 35,
    rootDepthCm: 20,
    light: "partial-shade",
    water: "high",
    soil: ["loamy"],
    goodCompanions: ["tomat", "boenner", "hvidkaal", "porre"],
    badCompanions: ["gulerod", "pastinak"],
    rotationYears: 3,
    icon: "🥬",
    forestGardenLayer: "root",
    source: "builtin",
  },
  {
    id: "fennikel",
    name: "Fennikel",
    latinName: "Foeniculum vulgare",
    category: "vegetable",
    subCategory: "other",
    family: "apiaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 5, to: 6 },
    harvest: { from: 8, to: 10 },
    spacingCm: 30,
    rowSpacingCm: 40,
    rootDepthCm: 30,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: [],
    badCompanions: ["tomat", "boenner", "aert", "dild"],
    rotationYears: 3,
    icon: "🌿",
    nutrition: { kcal: 31, proteinG: 1.2, fatG: 0.2, carbG: 7, fiberG: 3.1, highlights: "C-vitamin, kalium og anetol (god for fordøjelsen)." },
    description: "Fennikel er en dårlig nabo til de fleste afgrøder – plant den i sin egen del af haven.",
    forestGardenLayer: "root",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // URTER
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "basilikum",
    name: "Basilikum",
    latinName: "Ocimum basilicum",
    category: "herb",
    family: "lamiaceae",
    lifecycle: "annual",
    sowIndoor: { from: 3, to: 4 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 6, to: 9 },
    spacingCm: 20,
    rowSpacingCm: 30,
    rootDepthCm: 15,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    minTempC: 10,
    goodCompanions: ["tomat", "peber", "agurk"],
    badCompanions: ["salvie"],
    rotationYears: 0,
    icon: "🌿",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "persille",
    name: "Persille",
    latinName: "Petroselinum crispum",
    category: "herb",
    family: "apiaceae",
    lifecycle: "biennial",
    sowOutdoor: { from: 3, to: 6 },
    harvest: { from: 5, to: 10 },
    spacingCm: 15,
    rowSpacingCm: 25,
    rootDepthCm: 20,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["tomat", "gulerod", "roser"],
    badCompanions: ["salat"],
    rotationYears: 0,
    icon: "🌿",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "dild",
    name: "Dild",
    latinName: "Anethum graveolens",
    category: "herb",
    family: "apiaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 4, to: 7 },
    harvest: { from: 6, to: 9 },
    spacingCm: 15,
    rowSpacingCm: 25,
    rootDepthCm: 15,
    light: "full-sun",
    water: "low",
    soil: ["loamy", "sandy"],
    goodCompanions: ["agurk", "salat", "broccoli", "hvidkaal"],
    badCompanions: ["gulerod", "tomat", "fennikel"],
    rotationYears: 0,
    icon: "🌿",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "rosmarin",
    name: "Rosmarin",
    latinName: "Salvia rosmarinus",
    category: "herb",
    family: "lamiaceae",
    lifecycle: "perennial",
    plantOut: { from: 4, to: 5 },
    harvest: { from: 1, to: 12 },
    spacingCm: 60,
    rowSpacingCm: 60,
    rootDepthCm: 30,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "chalky"],
    goodCompanions: ["broccoli", "hvidkaal", "boenner", "gulerod"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌿",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "timian",
    name: "Timian",
    latinName: "Thymus vulgaris",
    category: "herb",
    family: "lamiaceae",
    lifecycle: "perennial",
    plantOut: { from: 4, to: 5 },
    harvest: { from: 4, to: 10 },
    spacingCm: 30,
    rowSpacingCm: 30,
    rootDepthCm: 15,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "chalky"],
    goodCompanions: ["tomat", "broccoli", "jordbeer"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌿",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "salvie",
    name: "Salvie",
    latinName: "Salvia officinalis",
    category: "herb",
    family: "lamiaceae",
    lifecycle: "perennial",
    plantOut: { from: 4, to: 5 },
    harvest: { from: 4, to: 10 },
    spacingCm: 45,
    rowSpacingCm: 45,
    rootDepthCm: 25,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "chalky"],
    goodCompanions: ["broccoli", "hvidkaal", "gulerod"],
    badCompanions: ["basilikum", "agurk"],
    rotationYears: 0,
    icon: "🌿",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "mynte",
    name: "Mynte",
    latinName: "Mentha spp.",
    category: "herb",
    family: "lamiaceae",
    lifecycle: "perennial",
    plantOut: { from: 4, to: 5 },
    harvest: { from: 4, to: 10 },
    spacingCm: 30,
    rowSpacingCm: 40,
    rootDepthCm: 15,
    light: "partial-shade",
    water: "high",
    soil: ["loamy", "any"],
    goodCompanions: ["tomat", "broccoli"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌿",
    description: "Spreder sig kraftigt – plant helst i krukke eller afgrænset bed.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "oregano",
    name: "Oregano",
    latinName: "Origanum vulgare",
    category: "herb",
    family: "lamiaceae",
    lifecycle: "perennial",
    plantOut: { from: 4, to: 5 },
    harvest: { from: 5, to: 10 },
    spacingCm: 30,
    rowSpacingCm: 40,
    rootDepthCm: 15,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "chalky"],
    goodCompanions: ["tomat", "peber"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌿",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FRUGT & BÆR
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "jordbeer",
    name: "Jordbær",
    latinName: "Fragaria × ananassa",
    category: "fruit",
    family: "rosaceae",
    lifecycle: "perennial",
    plantOut: { from: 4, to: 5 },
    harvest: { from: 6, to: 8 },
    spacingCm: 35,
    rowSpacingCm: 60,
    rootDepthCm: 20,
    spreadDiameterCm: 40,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "sandy"],
    goodCompanions: ["loeg", "hvidloeg", "purloeg", "spinat", "salat", "timian"],
    badCompanions: ["broccoli", "hvidkaal"],
    rotationYears: 4,
    icon: "🍓",
    difficulty: "easy",
    taste: "Sød, aromatisk, saftig. Hjemmedyrket har langt mere smag end købe-jordbær.",
    culinaryUses: "Frisk spisning, med fløde, i kage, syltetøj, smoothie, is, sauce til dessert.",
    harvestTips: "Høst når bærret er rødt hele vejen rundt. Pluk om morgenen for bedste smag. Løft bærret — træk ikke.",
    fertilizerInfo: "Gød med kompost i april og efter høst. Kaliumrig gødning under blomstring.",
    pests: ["Snegle", "Fugletyveri", "Jordbærmider"],
    diseases: ["Gråskimmel", "Meldug", "Rødmarv"],
    storageInfo: "Meget kort holdbarhed (2-3 dage i køleskab). Fryses nemt. Perfekt til syltetøj.",
    nutrition: { kcal: 32, proteinG: 0.7, fatG: 0.3, carbG: 8, fiberG: 2.0, highlights: "C-vitamin (mere end appelsin!), mangan, folat og antioxidanter." },
    varieties: [
      { id: "elsanta", name: "Elsanta", description: "Mest dyrkede sort i Europa. Pålidelig og god smag.", daysToHarvest: 80, taste: "Sød, balanceret syre", color: "lysrød", storageQuality: "good" },
      { id: "honeoye", name: "Honeoye", description: "Tidlig sort med store bær. God til nordisk klima.", daysToHarvest: 70, taste: "Sød-syrlig", color: "mørkrød", storageQuality: "fair" },
      { id: "korona", name: "Korona", description: "Hollandsk sort med fremragende smag og aroma.", daysToHarvest: 80, taste: "Meget aromatisk, sød", color: "rød", storageQuality: "fair" },
      { id: "malling-centenary", name: "Malling Centenary", description: "Nyere sort med store, faste bær og god sygdomsresistens.", daysToHarvest: 85, taste: "Sød, fyldig", color: "rød", resistances: ["meldug", "rødmarv"], storageQuality: "good" },
      { id: "ostara", name: "Ostara", description: "Remonterende (giver bær hele sommeren). Mindre men mange bær.", daysToHarvest: 90, taste: "Aromatisk, sød", color: "rød", storageQuality: "poor" },
    ],
    forestGardenLayer: "ground-cover",
    source: "builtin",
  },
  {
    id: "hindbeer",
    name: "Hindbær",
    latinName: "Rubus idaeus",
    category: "fruit",
    family: "rosaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 6, to: 9 },
    spacingCm: 50,
    rowSpacingCm: 150,
    rootDepthCm: 40,
    spreadDiameterCm: 100,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["hvidloeg", "purloeg"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🫐",
    nutrition: { kcal: 52, proteinG: 1.2, fatG: 0.7, carbG: 12, fiberG: 6.5, highlights: "Højt fiberindhold, C-vitamin, mangan og ellagsyre (antioxidant)." },
    forestGardenLayer: "shrub",
    source: "builtin",
  },
  {
    id: "solbaer",
    name: "Solbær",
    latinName: "Ribes nigrum",
    category: "fruit",
    family: "other",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 7, to: 8 },
    spacingCm: 120,
    rowSpacingCm: 150,
    rootDepthCm: 50,
    spreadDiameterCm: 150,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["purloeg", "hvidloeg", "morgenfrue"],
    badCompanions: ["kartoffel"],
    rotationYears: 0,
    icon: "🫐",
    nutrition: { kcal: 63, proteinG: 1.4, fatG: 0.4, carbG: 15, fiberG: 4.0, highlights: "Ekstremt C-vitaminrigt (3× appelsin), antocyaniner og jern." },
    forestGardenLayer: "shrub",
    source: "builtin",
  },
  {
    id: "ribs",
    name: "Ribs",
    latinName: "Ribes rubrum",
    category: "fruit",
    family: "other",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 7, to: 8 },
    spacingCm: 120,
    rowSpacingCm: 150,
    rootDepthCm: 40,
    spreadDiameterCm: 150,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["purloeg", "hvidloeg"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🔴",
    nutrition: { kcal: 56, proteinG: 1.4, fatG: 0.2, carbG: 14, fiberG: 4.3, highlights: "C-vitamin, K-vitamin, mangan og antioxidanter." },
    forestGardenLayer: "shrub",
    source: "builtin",
  },
  {
    id: "stikkelsbeer",
    name: "Stikkelsbær",
    latinName: "Ribes uva-crispa",
    category: "fruit",
    family: "other",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 7, to: 8 },
    spacingCm: 120,
    rowSpacingCm: 150,
    rootDepthCm: 40,
    spreadDiameterCm: 150,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["purloeg"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🟢",
    nutrition: { kcal: 44, proteinG: 0.9, fatG: 0.6, carbG: 10, fiberG: 4.3, highlights: "C-vitamin, kostfibre, mangan og antioxidanter." },
    forestGardenLayer: "shrub",
    source: "builtin",
  },
  {
    id: "blaabaer",
    name: "Blåbær",
    latinName: "Vaccinium corymbosum",
    category: "fruit",
    family: "other",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 7, to: 8 },
    spacingCm: 100,
    rowSpacingCm: 150,
    rootDepthCm: 30,
    spreadDiameterCm: 120,
    light: "full-sun",
    water: "high",
    soil: ["peaty"],
    phRange: { min: 4.0, max: 5.5 },
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🫐",
    nutrition: { kcal: 57, proteinG: 0.7, fatG: 0.3, carbG: 14, fiberG: 2.4, highlights: "Antocyaniner (hjernesundhed), C-vitamin, K-vitamin og mangan." },
    description: "Kræver sur jord (pH 4–5.5). Plant i rhododendronjord eller tilsæt svovl.",
    forestGardenLayer: "shrub",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BLOMSTER (nytteplanter)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "morgenfrue",
    name: "Morgenfrue",
    latinName: "Calendula officinalis",
    category: "flower",
    family: "asteraceae",
    lifecycle: "annual",
    sowOutdoor: { from: 4, to: 6 },
    harvest: { from: 6, to: 10 },
    spacingCm: 25,
    rowSpacingCm: 30,
    rootDepthCm: 15,
    light: "full-sun",
    water: "low",
    soil: ["any"],
    goodCompanions: ["tomat", "squash", "solbaer"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌼",
    description: "Tiltrækker bestøvere og afskrækker bladlus. Fantastisk fællesplante i grøntsagsbedet.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "solsikke",
    name: "Solsikke",
    latinName: "Helianthus annuus",
    category: "flower",
    family: "asteraceae",
    lifecycle: "annual",
    sowOutdoor: { from: 4, to: 5 },
    harvest: { from: 8, to: 10 },
    spacingCm: 45,
    rowSpacingCm: 60,
    rootDepthCm: 40,
    light: "full-sun",
    water: "medium",
    soil: ["any"],
    goodCompanions: ["agurk", "boenner"],
    badCompanions: ["kartoffel"],
    rotationYears: 0,
    icon: "🌻",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "tagetes",
    name: "Tagetes / Fløjlsblomst",
    latinName: "Tagetes spp.",
    category: "flower",
    family: "asteraceae",
    lifecycle: "annual",
    sowIndoor: { from: 3, to: 4 },
    plantOut: { from: 5, to: 6 },
    harvest: { from: 6, to: 10 },
    spacingCm: 20,
    rowSpacingCm: 30,
    rootDepthCm: 15,
    light: "full-sun",
    water: "low",
    soil: ["any"],
    goodCompanions: ["tomat", "kartoffel", "boenner"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌺",
    description: "Afskrækker nematoder i jorden og mange skadedyr. Plant langs bedkanter.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "lavendel",
    name: "Lavendel",
    latinName: "Lavandula angustifolia",
    category: "flower",
    family: "lamiaceae",
    lifecycle: "perennial",
    plantOut: { from: 4, to: 5 },
    harvest: { from: 6, to: 8 },
    spacingCm: 40,
    rowSpacingCm: 60,
    rootDepthCm: 25,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "chalky"],
    goodCompanions: ["roser"],
    badCompanions: [],
    rotationYears: 0,
    icon: "💜",
    forestGardenLayer: "shrub",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TRÆER (frugt)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "aeble",
    name: "Æbletræ",
    latinName: "Malus domestica",
    category: "tree",
    family: "rosaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 8, to: 10 },
    spacingCm: 400,
    rootDepthCm: 100,
    spreadDiameterCm: 500,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["purloeg", "morgenfrue", "lavendel"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🍎",
    difficulty: "medium",
    taste: "Sød til syrlig, sprød til blød — enorm variation mellem sorter.",
    culinaryUses: "Frisk spisning, æblekage, tarte tatin, æblemost, cider, kompot, tørrede æbleringe, chutney.",
    harvestTips: "Løft æblet vandret og drej let — modent æble slipper nemt. Kernerne skal være mørkebrune.",
    soilAmendments: "Dyb, næringsrig jord. Mulch årligt med kompost i fodrådszone.",
    fertilizerInfo: "Gød med kompost og algægødning i marts. Undgå gødning efter juni (ellers blødt træ inden vinter).",
    pests: ["Æblevikler", "Bladlus", "Røde edderkopmider"],
    diseases: ["Æbleskurv", "Meldug", "Knækkefodsyge (kræft)"],
    storageInfo: "Sene sorter kan lagres 3-6 mdr. i kølig kælder (2-4°C). Tidlige sorter spises hurtigt.",
    nutrition: { kcal: 52, proteinG: 0.3, fatG: 0.2, carbG: 14, fiberG: 2.4, highlights: "Kostfibre, C-vitamin, quercetin (antioxidant). An apple a day." },
    varieties: [
      { id: "discovery", name: "Discovery", description: "Tidlig dansk favori, sprød og saftig. Høstes august.", taste: "Sød-syrlig, sprød", color: "rød/grøn", storageQuality: "poor" },
      { id: "filippa", name: "Filippa", description: "Gammel dansk sort, blød og aromatisk. God til æblekage.", taste: "Syrlig, aromatisk", color: "grøn/rød", storageQuality: "fair" },
      { id: "cox-orange", name: "Cox Orange", description: "Verdens bedste spiseæble ifølge mange. Kompleks, rig smag.", taste: "Aromatisk, sprød, sød-syrlig", color: "orange-rød", storageQuality: "fair" },
      { id: "belle-de-boskoop", name: "Belle de Boskoop", description: "Stor, syrlig, perfekt til madlavning og æblemost.", taste: "Syrlig, fast kød", color: "grøn/rød", storageQuality: "excellent" },
      { id: "elstar", name: "Elstar", description: "Populær alsidigt æble med god balance.", taste: "Sød-syrlig, saftig", color: "rød/gul", storageQuality: "good" },
      { id: "graesten", name: "Gråsten", description: "Den mest danske af alle æbler. Så stor at 2-3 giver en kage.", taste: "Syrlig, blød", color: "grøn", storageQuality: "poor" },
    ],
    forestGardenLayer: "sub-canopy",
    source: "builtin",
  },
  {
    id: "paere",
    name: "Pæretræ",
    latinName: "Pyrus communis",
    category: "tree",
    family: "rosaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 8, to: 10 },
    spacingCm: 400,
    rootDepthCm: 100,
    spreadDiameterCm: 400,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["purloeg", "morgenfrue"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🍐",
    nutrition: { kcal: 57, proteinG: 0.4, fatG: 0.1, carbG: 15, fiberG: 3.1, highlights: "Kostfibre (pektin), C-vitamin, K-vitamin og kobber." },
    forestGardenLayer: "sub-canopy",
    source: "builtin",
  },
  {
    id: "kirsebeer",
    name: "Kirsebærtræ",
    latinName: "Prunus avium",
    category: "tree",
    family: "rosaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 6, to: 7 },
    spacingCm: 500,
    rootDepthCm: 100,
    spreadDiameterCm: 600,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "chalky"],
    goodCompanions: ["purloeg"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🍒",
    nutrition: { kcal: 63, proteinG: 1.1, fatG: 0.2, carbG: 16, fiberG: 2.1, highlights: "Antocyaniner, C-vitamin, kalium og melatonin (søvnfremmer)." },
    forestGardenLayer: "sub-canopy",
    source: "builtin",
  },
  {
    id: "blomme",
    name: "Blommetræ",
    latinName: "Prunus domestica",
    category: "tree",
    family: "rosaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 8, to: 9 },
    spacingCm: 400,
    rootDepthCm: 80,
    spreadDiameterCm: 400,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["purloeg"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🟣",
    nutrition: { kcal: 46, proteinG: 0.7, fatG: 0.3, carbG: 11, fiberG: 1.4, highlights: "C-vitamin, K-vitamin, kalium og antioxidanter. Tørrede (svesker) rige på fibre." },
    forestGardenLayer: "sub-canopy",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TRÆER (løv- og prydtræer)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "eg",
    name: "Eg",
    latinName: "Quercus robur",
    category: "tree",
    family: "fagaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 1000,
    rootDepthCm: 200,
    spreadDiameterCm: 1250,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay", "sandy"],
    frostHardy: true,
    goodCompanions: ["hassel", "roennebeer"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌳",
    difficulty: "easy",
    description: "Stilk-Eg — Danmarks nationaltræ. Kan blive over 1000 år gammel og huser op mod 2000 insektarter.",
    harvestTips: "Agern kan samles i okt-nov. De kan spises ristet efter udblødning (fjerner garvesyre).",
    soilAmendments: "Trives i de fleste jordtyper. Dybt rodnet, tørketolerant som voksen.",
    pests: ["Egebladruller", "Egegalmyg", "Egeprocessionsspinder"],
    diseases: ["Egemeldug", "Honningsvamp"],
    varieties: [
      { id: "fastigiata", name: "Fastigiata", description: "Søjle-eg med smalt, opstående vækst. Perfekt til allé eller smal have.", heightCm: 1500 },
      { id: "concordia", name: "Concordia", description: "Gul-løvet eg. Lysegrønt til gyldengrønt løv hele sæsonen.", heightCm: 1000 },
      { id: "quercus-rubra", name: "Rødeg", description: "Nordamerikansk art med fantastisk rød efterårsfarve.", heightCm: 2500 },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "boeg",
    name: "Bøg",
    latinName: "Fagus sylvatica",
    category: "tree",
    family: "fagaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 800,
    rootDepthCm: 150,
    spreadDiameterCm: 1000,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy", "chalky"],
    frostHardy: true,
    goodCompanions: ["eg", "kristtorn"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌳",
    difficulty: "easy",
    description: "Dansk skovtræ nr. 1. Smukt lysegrønt forår, gyldent efterår. Perfekt hæk — holder de brune blade vinteren over.",
    harvestTips: "Bog (bøgenødder) er spiselige og olierige. Samles i september-oktober.",
    soilAmendments: "Foretrækker drænet, kalkholdig jord. Danner skygge der undertrykker ukrudt.",
    pests: ["Bøgebladlus", "Bøgebarkbille"],
    diseases: ["Bøgebarksvamp", "Bøgekræft"],
    varieties: [
      { id: "purpurea", name: "Blodbøg", description: "Dybmørkerødt løv. Meget populær som solitær og hæk.", heightCm: 2500, color: "mørkerød" },
      { id: "pendula", name: "Hængebøg", description: "Dramatisk hængende grene. Stort solitærtræ til parkhaver.", heightCm: 2000 },
      { id: "dawyck", name: "Dawyck", description: "Søjleformet bøg, smal og elegant. God til mindre haver.", heightCm: 1500 },
      { id: "tricolor", name: "Tricolor", description: "Lilla-rosa-hvid-broget løv. Exceptionelt smukt prydtræ.", heightCm: 800, color: "lilla/rosa/hvid" },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "birk",
    name: "Birk",
    latinName: "Betula pendula",
    category: "tree",
    family: "betulaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 600,
    rootDepthCm: 100,
    spreadDiameterCm: 750,
    light: "full-sun",
    water: "medium",
    soil: ["sandy", "loamy", "peaty"],
    frostHardy: true,
    goodCompanions: ["roennebeer"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌳",
    difficulty: "easy",
    description: "Vortebirk — elegant pionertræ med hvid bark og let, luftig krone. Hurtigvoksende og nøjsomt.",
    harvestTips: "Birkesaft tappes i marts inden løvspring ved at bore et lille hul i stammen.",
    soilAmendments: "Trives i mager jord. Rødder forbedrer kompakt jord. Pionertræ der etablerer sig hurtigt.",
    pests: ["Birkebladveps", "Bladminerere"],
    diseases: ["Birkerust", "Honningsvamp"],
    varieties: [
      { id: "youngii", name: "Youngii (Hængebirk)", description: "Lille hængende birk med parasolform. Maks 8 m. Perfekt til forhaver.", heightCm: 800 },
      { id: "jacquemontii", name: "Jacquemontii (Himalayabirk)", description: "Kridhvid bark — det hvideste af alle birketræer. Fantastisk vinterdekoration.", heightCm: 1200, color: "kridhvid bark" },
      { id: "dalecarlica", name: "Dalecarlica (Ornäsbirk)", description: "Svensk birk med dybt fligede blade. Elegant og sjælden.", heightCm: 1500 },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "pil",
    name: "Pil",
    latinName: "Salix alba",
    category: "tree",
    family: "salicaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 800,
    rootDepthCm: 200,
    spreadDiameterCm: 1000,
    light: "full-sun",
    water: "high",
    soil: ["loamy", "clay", "peaty"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌳",
    difficulty: "easy",
    description: "Hvidpil — hurtigvoksende vandkærende træ. Fantastisk til fugtige hjørner. Barken indeholder salicin (naturlig aspirin).",
    soilAmendments: "Elsker fugt, klarer sig ved åer, søer og våde bede. Rødder søger vand — plant langt fra kloaker.",
    pests: ["Pilebladbille", "Bladlus"],
    diseases: ["Pileskurv", "Pilebladrust"],
    varieties: [
      { id: "tristis", name: "Hængepil", description: "Salix × sepulcralis 'Chrysocoma'. Det ikoniske hængende piletræ ved gadekæret.", heightCm: 1500 },
      { id: "purpurea", name: "Rødpil", description: "Salix purpurea. Mindre buskagtig pil med rødlige skud. God til fletning.", heightCm: 500 },
      { id: "babylonica-tortuosa", name: "Snoet Pil", description: "Salix babylonica 'Tortuosa'. Snoede grene giver skulpturel vintereffekt.", heightCm: 800 },
      { id: "viminalis", name: "Båndpil", description: "Salix viminalis. Traditionel fletpil. Hurtig genvækst efter stævning.", heightCm: 600 },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "ahorn",
    name: "Ahorn",
    latinName: "Acer platanoides",
    category: "tree",
    family: "sapindaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 800,
    rootDepthCm: 150,
    spreadDiameterCm: 1000,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay", "chalky"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🍁",
    difficulty: "easy",
    description: "Spidsløn — stort smukt allétræ med gule blomster i april og intens gul efterårsfarve. Meget vindfast.",
    soilAmendments: "Tolerant overfor de fleste jordtyper. Stærkt og vindfast. God skyggedanner.",
    pests: ["Ahornbladlus"],
    diseases: ["Meldug", "Tjærepletsvamp (harmløs)"],
    varieties: [
      { id: "crimson-king", name: "Crimson King", description: "Mørkerødlilla løv hele sæsonen. Meget populært prydtræ.", heightCm: 1500, color: "mørkerød" },
      { id: "globosum", name: "Globosum (Kugleahorn)", description: "Kompakt kugleformet krone uden beskæring. Perfekt til mindre haver og indkørsler.", heightCm: 500 },
      { id: "drummondii", name: "Drummondii", description: "Hvidbrogede blade — lyser markant op. Elegant og anderledes.", heightCm: 1000, color: "grøn/hvid" },
      { id: "acer-ginnala", name: "Ildløn", description: "Acer tataricum subsp. ginnala. Lille træ/stor busk med knaldrød efterårsfarve.", heightCm: 600, color: "knaldrød (efterår)" },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "ask",
    name: "Ask",
    latinName: "Fraxinus excelsior",
    category: "tree",
    family: "oleaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 1000,
    rootDepthCm: 200,
    spreadDiameterCm: 1250,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay", "chalky"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌳",
    difficulty: "medium",
    description: "Europæisk ask — ædelt, hurtigt voksende træ. Norrøn mytologi: Yggdrasil var en ask. OBS: Asketoptørre (Hymenoscyphus fraxineus) er et alvorligt problem.",
    soilAmendments: "Foretrækker fugtig, næringsrig jord. Dybt rodnet.",
    pests: ["Askefrøgalmyg", "Askebarkbille"],
    diseases: ["Asketoptørre (Hymenoscyphus fraxineus)"],
    varieties: [
      { id: "pendula", name: "Hængeask", description: "Fraxinus excelsior 'Pendula'. Kompakt hængende form. Populært havetræ.", heightCm: 600 },
      { id: "jaspidea", name: "Guldask", description: "Gule skud om vinteren og gulligt løv. Lyser haven op.", heightCm: 1500, color: "gul" },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "lind",
    name: "Lind",
    latinName: "Tilia cordata",
    category: "tree",
    family: "tiliaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 800,
    rootDepthCm: 150,
    spreadDiameterCm: 1000,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy", "clay"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌳",
    difficulty: "easy",
    description: "Småbladet lind — klassisk dansk allé- og bytræ. Dufter fantastisk i juni-juli når den blomstrer. Bier elsker den.",
    harvestTips: "Lindeblomster høstes i juni-juli til te (beroligende, svedrivende). Tørres i skygge.",
    soilAmendments: "Tolerant og nem. Tåler beskæring godt — klassisk formet som kugle eller søjle.",
    pests: ["Lindebladlus (producerer honningdug)"],
    diseases: ["Lindebladpletsvamp"],
    varieties: [
      { id: "greenspire", name: "Greenspire", description: "Tilia cordata 'Greenspire'. Klassisk symmetrisk form. Den mest plantede lind i Danmark.", heightCm: 1500 },
      { id: "rancho", name: "Rancho", description: "Kompakt pyramideform. God til mindre haver og gader.", heightCm: 1000 },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "roennebeer",
    name: "Rønnebær",
    latinName: "Sorbus aucuparia",
    category: "tree",
    family: "rosaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    harvest: { from: 8, to: 9 },
    spacingCm: 400,
    rootDepthCm: 80,
    spreadDiameterCm: 500,
    light: "full-sun",
    water: "medium",
    soil: ["sandy", "loamy", "peaty"],
    frostHardy: true,
    goodCompanions: ["birk"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌳",
    difficulty: "easy",
    description: "Alm. røn — småt, flot træ med hvide blomster i maj og røde bær i aug-sep. Vigtigt fugletræ.",
    harvestTips: "Rønnebær bruges til gelé, saft og snaps. Koges altid (rå er bittersure). Høstes efter første frost.",
    soilAmendments: "Meget nøjsomt. Klarer mager, sur jord. God som pionertræ.",
    pests: ["Rønnesækkemøl"],
    diseases: ["Rønnerust", "Ildsot"],
    varieties: [
      { id: "edulis", name: "Mährische (Spiselig røn)", description: "Store, søde bær uden bitterhed. Bruges til saft, vin og gelé.", heightCm: 1000, taste: "Sød-syrlig" },
      { id: "dodong", name: "Dodong", description: "Koreansk art med fantastisk orange-rød efterårsfarve og store bladfjer.", heightCm: 800, color: "rød efterårsfarve" },
    ],
    forestGardenLayer: "sub-canopy",
    source: "builtin",
  },
  {
    id: "elm",
    name: "Elm",
    latinName: "Ulmus glabra",
    category: "tree",
    family: "ulmaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 1000,
    rootDepthCm: 200,
    spreadDiameterCm: 1250,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌳",
    difficulty: "medium",
    description: "Storbladet elm — smukt træ med asymmetriske blade. Delvist decimeret af elmesyge, men resistente sorter findes nu.",
    soilAmendments: "Foretrækker dyb, næringsrig jord. Tåler bysalt og forurening.",
    pests: ["Elmebarkbille (spreder elmesyge)"],
    diseases: ["Elmesyge (Ophiostoma novo-ulmi)"],
    varieties: [
      { id: "camperdownii", name: "Camperdownii (Parasolel)", description: "Hængende form der danner naturlig parasol. Dramatisk og flot.", heightCm: 600 },
      { id: "new-horizon", name: "New Horizon", description: "Resistent mod elmesyge. Sund og hurtigvoksende.", heightCm: 1500, resistances: ["elmesyge"] },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "valnoed",
    name: "Valnød",
    latinName: "Juglans regia",
    category: "tree",
    family: "juglandaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 9, to: 10 },
    spacingCm: 1000,
    rootDepthCm: 200,
    spreadDiameterCm: 800,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "chalky"],
    frostHardy: true,
    minTempC: -15,
    goodCompanions: [],
    badCompanions: ["aeble", "tomat"],
    rotationYears: 0,
    icon: "🌰",
    difficulty: "medium",
    description: "Ægte valnød — ædelt, langsomt træ med aromatiske nødder. Rødder udskiller juglon der hæmmer visse planters vækst.",
    harvestTips: "Nødder høstes når det grønne skjul revner og de falder ned. Tør i sol i 2-3 uger.",
    soilAmendments: "Dyb, veldrænet jord. Beskyttet, varm placering giver bedst frugt i DK.",
    pests: ["Valnødflue"],
    diseases: ["Valnødskimmel", "Bakteriebrand"],
    nutrition: { kcal: 654, proteinG: 15.2, fatG: 65.2, carbG: 14, fiberG: 6.7, highlights: "Omega-3 fedtsyrer (ALA), E-vitamin, folat, magnesium. Hjertesund superfood." },
    varieties: [
      { id: "broadview", name: "Broadview", description: "Canadisk sort. Selvbefrugtende, begynder at bære tidligt. God til dansk klima.", taste: "Mild, cremet" },
      { id: "buccaneer", name: "Buccaneer", description: "Hollandsk sort, robust og tidligt bærende. Bestøver for andre sorter.", taste: "Rig, nøddeagtig" },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "hassel",
    name: "Hassel",
    latinName: "Corylus avellana",
    category: "tree",
    family: "betulaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 3 },
    harvest: { from: 9, to: 10 },
    spacingCm: 400,
    rootDepthCm: 80,
    spreadDiameterCm: 400,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy", "chalky", "clay"],
    frostHardy: true,
    goodCompanions: ["eg"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌰",
    difficulty: "easy",
    description: "Hassel — oprindelig dansk busk/lille træ. Først blomstrende med rakler i februar. Vigtig for tidlige bier.",
    harvestTips: "Hasselnødder høstes i september når skallen er brun. Lad dem tørre 2-3 uger inden opbevaring.",
    soilAmendments: "Meget tolerant. God til skovhave, læhegn og som underbeplantning.",
    pests: ["Hasselnødsnudebille"],
    diseases: ["Hasselbladpletsvamp"],
    nutrition: { kcal: 628, proteinG: 15, fatG: 61, carbG: 17, fiberG: 9.7, highlights: "E-vitamin, mangan, kobber, folat. Rig på oliesyre (som olivenolie)." },
    varieties: [
      { id: "contorta", name: "Krølhassel", description: "Snoede, krøllede grene — fantastisk vintereffekt. Langsom vækst.", heightCm: 400 },
      { id: "purpurea", name: "Blodhassel", description: "Mørkerødt løv hele sæsonen. Smukt som solitær.", heightCm: 500, color: "mørkerød" },
      { id: "webb-prize-cob", name: "Webb's Prize Cob", description: "Storfrugtet, produktiv sort. Gode nødder til spisning.", taste: "Sød, cremet" },
    ],
    forestGardenLayer: "sub-canopy",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TRÆER (nåletræer)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "fyr",
    name: "Skovfyr",
    latinName: "Pinus sylvestris",
    category: "tree",
    family: "pinaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 600,
    rootDepthCm: 150,
    spreadDiameterCm: 750,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "loamy"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌲",
    difficulty: "easy",
    description: "Skovfyr — markant silhuet med kobberrød bark øverst. Danmarks eneste oprindelige nåletræ. Ekstremt nøjsomt og vindfast.",
    soilAmendments: "Klarer mager, sandet jord. Tørketolerant. Perfekt til kystplantninger og hedeområder.",
    pests: ["Fyrresnudebille", "Fyrrespinder"],
    diseases: ["Fyrrekræft", "Knækkesyge"],
    varieties: [
      { id: "watereri", name: "Watereri", description: "Kompakt, kegleformet form. Maks 4-5 m. God til mindre haver.", heightCm: 500 },
      { id: "fastigiata", name: "Fastigiata", description: "Smal søjleform. Unik blandt fyrtræer.", heightCm: 800 },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "gran",
    name: "Rødgran",
    latinName: "Picea abies",
    category: "tree",
    family: "pinaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 600,
    rootDepthCm: 80,
    spreadDiameterCm: 750,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy", "clay", "peaty"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🎄",
    difficulty: "easy",
    description: "Rødgran — det klassiske danske juletræ. Tæt, mørk krone. Hurtigvoksende. God læplantning men fladrodet (stormfølsom).",
    soilAmendments: "Trives i fugtig, sur jord. Tåler skygge som ung.",
    pests: ["Barkbille", "Granvæger"],
    diseases: ["Rodfordærver", "Nålesvampe"],
    varieties: [
      { id: "nidiformis", name: "Nidiformis (Redemgran)", description: "Flad, redeformet dværgform. Maks 1 m. Perfekt til stenhaver.", heightCm: 100 },
      { id: "inversa", name: "Inversa", description: "Hængende søjleform. Skulpturel og unik.", heightCm: 600 },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "taks",
    name: "Taks",
    latinName: "Taxus baccata",
    category: "tree",
    family: "taxaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 300,
    rootDepthCm: 80,
    spreadDiameterCm: 375,
    light: "shade",
    water: "medium",
    soil: ["loamy", "chalky", "clay"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌲",
    difficulty: "easy",
    description: "Taks — det eneste danske nåletræ der tåler kraftig skygge. Kan beskæres til enhver form. Ekstremt langsomt voksende og langlivet. ⚠️ GIFTIG — alle dele undtagen det røde frøkød er giftige.",
    soilAmendments: "Trives i kalk- og lerholdig jord. Fantastisk hækplante. Kan blive 2000+ år.",
    pests: ["Taksens galmyg"],
    diseases: ["Phytophthora (rodråd i vandlidende jord)"],
    varieties: [
      { id: "fastigiata", name: "Fastigiata (Søjletaks)", description: "Smal, søjleformet vækst. Klassisk engelsk havedesign.", heightCm: 500 },
      { id: "repandens", name: "Repandens", description: "Fladtvoksende bunddækkende taks. Maks 50 cm. God under store træer.", heightCm: 50 },
      { id: "fastigiata-aurea", name: "Fastigiata Aurea", description: "Gulrandet søjletaks. Lyser flot op i skygge.", heightCm: 400, color: "gulrandet" },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "thuja",
    name: "Thuja (Livstræ)",
    latinName: "Thuja occidentalis",
    category: "tree",
    family: "cupressaceae",
    lifecycle: "perennial",
    plantOut: { from: 9, to: 5 },
    spacingCm: 60,
    rootDepthCm: 60,
    spreadDiameterCm: 75,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌲",
    difficulty: "easy",
    description: "Thuja — Danmarks mest plantede hækplante. Tæt, stedsegrøn, hurtigvoksende. Kræver regelmæssig klipning.",
    soilAmendments: "God fugtig jord. Tåler ikke udtørring — taber nåle permanent.",
    pests: ["Thujaminerblad"],
    diseases: ["Kabatina (skudsvamp)", "Pestalotiopsis"],
    varieties: [
      { id: "smaragd", name: "Smaragd", description: "Kompakt, kegleformet, klar smaragdgrøn farve hele året. Behøver minimal klipning.", heightCm: 400, color: "smaragdgrøn" },
      { id: "brabant", name: "Brabant", description: "Hurtigvoksende (40-60 cm/år). Den mest brugte hækthua i DK.", heightCm: 1500 },
      { id: "danica", name: "Danica", description: "Kugleformet dværg. Maks 80 cm. God til bede og krukker.", heightCm: 80 },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },
  {
    id: "laerk",
    name: "Lærk",
    latinName: "Larix decidua",
    category: "tree",
    family: "pinaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    spacingCm: 600,
    rootDepthCm: 150,
    spreadDiameterCm: 750,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "sandy"],
    frostHardy: true,
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌲",
    difficulty: "easy",
    description: "Europæisk lærk — det eneste løvfældende nåletræ i dansk skovbrug. Lysegrønt forår, guldgult efterår. Meget holdbart træ.",
    soilAmendments: "Godt drænet jord. Lyskrævende, men hurtigt voksende.",
    pests: ["Lærkebladveps"],
    diseases: ["Lærkekræft"],
    varieties: [
      { id: "pendula", name: "Pendula", description: "Hængende form. Dramatisk vintertræ med nøgne, buede grene.", heightCm: 800 },
      { id: "japonica", name: "Japansk Lærk", description: "Larix kaempferi. Lidt bredere nåle og mere blågrøn. Robust.", heightCm: 2000 },
    ],
    forestGardenLayer: "canopy",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BUSKE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "roser",
    name: "Rose",
    latinName: "Rosa spp.",
    category: "bush",
    family: "rosaceae",
    lifecycle: "perennial",
    plantOut: { from: 10, to: 4 },
    harvest: { from: 6, to: 9 },
    spacingCm: 60,
    rootDepthCm: 50,
    spreadDiameterCm: 80,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["lavendel", "persille", "hvidloeg", "purloeg"],
    badCompanions: [],
    rotationYears: 0,
    icon: "🌹",
    forestGardenLayer: "shrub",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DÆKAFGRØDER
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "kloever",
    name: "Kløver (hvidkløver)",
    latinName: "Trifolium repens",
    category: "cover-crop",
    family: "fabaceae",
    lifecycle: "perennial",
    sowOutdoor: { from: 4, to: 8 },
    spacingCm: 0,
    light: "full-sun",
    water: "low",
    soil: ["any"],
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "☘️",
    description: "Kvælstoffikserende bunddække. God som grøngødning mellem rækker.",
    forestGardenLayer: "ground-cover",
    source: "builtin",
  },
  {
    id: "phacelia",
    name: "Phacelia / bivennen",
    latinName: "Phacelia tanacetifolia",
    category: "cover-crop",
    family: "other",
    lifecycle: "annual",
    sowOutdoor: { from: 4, to: 8 },
    harvest: { from: 6, to: 10 },
    spacingCm: 0,
    light: "full-sun",
    water: "low",
    soil: ["any"],
    goodCompanions: [],
    badCompanions: [],
    rotationYears: 0,
    icon: "💮",
    description: "Fantastisk bi-venlig dækafgrøde. Forbedrer jordstruktur og tiltrækker nyttedyr.",
    forestGardenLayer: "ground-cover",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STAUDER (perennial)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "lavendel-staude",
    name: "Lavendel",
    latinName: "Lavandula angustifolia",
    category: "perennial",
    family: "lamiaceae",
    lifecycle: "perennial",
    spacingCm: 40,
    rowSpacingCm: 60,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "loamy"],
    goodCompanions: ["rosmarin", "timian", "salvie"],
    badCompanions: [],
    icon: "💜",
    description: "Duftende, tørketolerant staude. Tiltrækker bier og sommerfugle. Klip tilbage om foråret.",
    forestGardenLayer: "shrub",
    source: "builtin",
  },
  {
    id: "echinacea",
    name: "Purpur-solhat",
    latinName: "Echinacea purpurea",
    category: "perennial",
    family: "asteraceae",
    lifecycle: "perennial",
    spacingCm: 45,
    rowSpacingCm: 50,
    light: "full-sun",
    water: "low",
    soil: ["loamy", "sandy"],
    goodCompanions: ["lavendel-staude", "rudbeckia"],
    badCompanions: [],
    icon: "🌸",
    description: "Robust, tørketolerant staude med store blomsterhoveder. Vigtig for bier og insekter. Bruges også som lægeplante.",
    forestGardenLayer: "shrub",
    source: "builtin",
  },
  {
    id: "rudbeckia",
    name: "Solhat (Rudbeckia)",
    latinName: "Rudbeckia fulgida",
    category: "perennial",
    family: "asteraceae",
    lifecycle: "perennial",
    spacingCm: 40,
    rowSpacingCm: 50,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["echinacea", "astilbe"],
    badCompanions: [],
    icon: "🌻",
    description: "Gule stråleblomster fra sensommer til efterår. Meget hårdfør og nem at dyrke.",
    forestGardenLayer: "shrub",
    source: "builtin",
  },
  {
    id: "hosta",
    name: "Funkia (Hosta)",
    latinName: "Hosta spp.",
    category: "perennial",
    family: "asparagaceae",
    lifecycle: "perennial",
    spacingCm: 50,
    rowSpacingCm: 60,
    light: "shade",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["astilbe", "bregne"],
    badCompanions: [],
    icon: "🌿",
    description: "Klassisk skyggestaude med dekorative blade i mange farver og størrelser. Snegle elsker dem – beskyt evt.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "astilbe",
    name: "Astilbe",
    latinName: "Astilbe × arendsii",
    category: "perennial",
    family: "saxifragaceae",
    lifecycle: "perennial",
    spacingCm: 40,
    rowSpacingCm: 45,
    light: "partial-shade",
    water: "high",
    soil: ["loamy", "clay"],
    goodCompanions: ["hosta", "bregne"],
    badCompanions: [],
    icon: "🪻",
    description: "Elegant staude med fjerlette blomsterstande i hvid, rosa og rød. Trives i fugtig halvskygge.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "paeonia",
    name: "Pæon (Bonderose)",
    latinName: "Paeonia lactiflora",
    category: "perennial",
    family: "paeoniaceae",
    lifecycle: "perennial",
    spacingCm: 80,
    rowSpacingCm: 90,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["lavendel-staude", "iris"],
    badCompanions: [],
    icon: "🌺",
    description: "Storblomstret, langlivet staude med fantastisk duft. Blomstrer i maj-juni. Kan leve i årtier på samme sted.",
    forestGardenLayer: "shrub",
    source: "builtin",
  },
  {
    id: "iris",
    name: "Iris (Sværdlilje)",
    latinName: "Iris germanica",
    category: "perennial",
    family: "iridaceae",
    lifecycle: "perennial",
    spacingCm: 35,
    rowSpacingCm: 45,
    light: "full-sun",
    water: "low",
    soil: ["loamy", "sandy"],
    goodCompanions: ["paeonia", "lavendel-staude"],
    badCompanions: [],
    icon: "💙",
    description: "Elegant staude med sværdformede blade og iøjnefaldende blomster i mange farver. Tørketolerant.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "geranium-staude",
    name: "Storkenæb (Geranium)",
    latinName: "Geranium × magnificum",
    category: "perennial",
    family: "geraniaceae",
    lifecycle: "perennial",
    spacingCm: 40,
    rowSpacingCm: 45,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy", "clay", "sandy"],
    goodCompanions: ["hosta", "astilbe", "roser"],
    badCompanions: [],
    icon: "🌸",
    description: "Alsidigt bunddække med masser af blomster fra maj til frost. Meget hårdfør og sygdomsfri.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "bregne",
    name: "Bregne (Dryopteris)",
    latinName: "Dryopteris filix-mas",
    category: "perennial",
    family: "dryopteridaceae",
    lifecycle: "perennial",
    spacingCm: 50,
    rowSpacingCm: 60,
    light: "shade",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["hosta", "astilbe"],
    badCompanions: [],
    icon: "🌿",
    description: "Mangebregne – klassisk skyggeplante med elegant bladvækst. Hårdfør, nem og næsten vedligeholdelsesfri.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "daglilje",
    name: "Daglilje",
    latinName: "Hemerocallis spp.",
    category: "perennial",
    family: "asphodelaceae",
    lifecycle: "perennial",
    spacingCm: 45,
    rowSpacingCm: 50,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["echinacea", "rudbeckia"],
    badCompanions: [],
    icon: "🧡",
    description: "Uimodståelig blomsterpragt hele sommeren. Hver blomst lever kun én dag, men nye springer ud dagligt. Totalt hårdfør.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRÆSSER (grass)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "pampasgras",
    name: "Pampasgræs",
    latinName: "Cortaderia selloana",
    category: "grass",
    family: "poaceae",
    lifecycle: "perennial",
    spacingCm: 150,
    rowSpacingCm: 150,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "loamy"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🌾",
    description: "Ikonisk prydgræs med store, silkeagtige blomstertoppe op til 2-3 m. Beskyt mod frost de første år. Klip ned i marts.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "blaasvingel",
    name: "Blåsvingel",
    latinName: "Festuca glauca",
    category: "grass",
    family: "poaceae",
    lifecycle: "perennial",
    spacingCm: 25,
    rowSpacingCm: 30,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "loamy"],
    goodCompanions: ["lavendel-staude", "echinacea"],
    badCompanions: [],
    icon: "🔵",
    description: "Kompakt, blågrønt tuegræs (ca. 30 cm). Fantastisk i stenbede og som kantplante. Tørketolerant.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "japansk-blodgraes",
    name: "Japansk Blodgræs",
    latinName: "Imperata cylindrica 'Red Baron'",
    category: "grass",
    family: "poaceae",
    lifecycle: "perennial",
    spacingCm: 30,
    rowSpacingCm: 35,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🔴",
    description: "Oprette, smalle blade der farves blodrøde fra spidsen i løbet af sommeren. 40-50 cm høj. Effektfuld i grupper.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "elefantgraes",
    name: "Elefantgræs (Miscanthus)",
    latinName: "Miscanthus sinensis",
    category: "grass",
    family: "poaceae",
    lifecycle: "perennial",
    spacingCm: 100,
    rowSpacingCm: 120,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🌾",
    description: "Stort, elegant prydgræs (1,5–2,5 m) med sølvhvide blomstertoppe. Perfekt som hæk eller solitær. Klip ned i marts.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "stipa",
    name: "Fjergræs",
    latinName: "Stipa tenuissima",
    category: "grass",
    family: "poaceae",
    lifecycle: "perennial",
    spacingCm: 30,
    rowSpacingCm: 35,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "loamy"],
    goodCompanions: ["lavendel-staude", "blaasvingel"],
    badCompanions: [],
    icon: "🌬️",
    description: "Blødt, bølgende græs med silkeagtige aks. Bevæger sig smukt i vinden. 40-60 cm. Tørketolerant og selvssående.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "molinia",
    name: "Blåtop",
    latinName: "Molinia caerulea",
    category: "grass",
    family: "poaceae",
    lifecycle: "perennial",
    spacingCm: 50,
    rowSpacingCm: 60,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["echinacea", "rudbeckia"],
    badCompanions: [],
    icon: "🌾",
    description: "Elegant dansk prydgræs med lette, luftige blomsterstande. Flot gylden høstfarve. Op til 1,5 m.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "carex",
    name: "Star (Carex)",
    latinName: "Carex morrowii",
    category: "grass",
    family: "cyperaceae",
    lifecycle: "perennial",
    spacingCm: 30,
    rowSpacingCm: 35,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["hosta", "bregne"],
    badCompanions: [],
    icon: "🌿",
    description: "Stedsegrønt skyggetolerant græs. Perfekt som bunddække eller kantplante. 30-40 cm. Meget hårdfør.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // KLATREPLANTER (climber)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "klematis",
    name: "Klematis",
    latinName: "Clematis spp.",
    category: "climber",
    family: "ranunculaceae",
    lifecycle: "perennial",
    spacingCm: 60,
    rowSpacingCm: 100,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["klatrerose"],
    badCompanions: [],
    icon: "🌸",
    description: "Havens dronning blandt klatreplanter. Hundredvis af sorter i alle farver. Husk: 'Foden i skygge, hovedet i sol.'",
    forestGardenLayer: "climber",
    source: "builtin",
  },
  {
    id: "klatrerose",
    name: "Klatrerose",
    latinName: "Rosa spp. (climbing)",
    category: "climber",
    family: "rosaceae",
    lifecycle: "perennial",
    spacingCm: 100,
    rowSpacingCm: 150,
    light: "full-sun",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: ["klematis", "lavendel-staude"],
    badCompanions: [],
    icon: "🌹",
    description: "Romantisk klatreplante med duftende blomster. Kræver espalier eller pergola. Beskær i marts.",
    forestGardenLayer: "climber",
    source: "builtin",
  },
  {
    id: "vedbend",
    name: "Vedbend (Efeu)",
    latinName: "Hedera helix",
    category: "climber",
    family: "araliaceae",
    lifecycle: "perennial",
    spacingCm: 50,
    rowSpacingCm: 60,
    light: "shade",
    water: "low",
    soil: ["loamy", "clay", "sandy"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🌿",
    description: "Stedsegrøn, selvhæftende klatreplante. Klatrer op ad mure og hegn. Kan være invasiv – hold den i kontrol.",
    forestGardenLayer: "climber",
    source: "builtin",
  },
  {
    id: "kaprifolie",
    name: "Kaprifolie",
    latinName: "Lonicera caprifolium",
    category: "climber",
    family: "caprifoliaceae",
    lifecycle: "perennial",
    spacingCm: 80,
    rowSpacingCm: 100,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: ["klematis"],
    badCompanions: [],
    icon: "🌼",
    description: "Vidunderlig duftende klatreplante, især om aftenen. Blomstrer i juni-juli. Tiltrækker natsværmere.",
    forestGardenLayer: "climber",
    source: "builtin",
  },
  {
    id: "blaaregn",
    name: "Blåregn",
    latinName: "Wisteria sinensis",
    category: "climber",
    family: "fabaceae",
    lifecycle: "perennial",
    spacingCm: 200,
    rowSpacingCm: 300,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: [],
    badCompanions: [],
    icon: "💜",
    description: "Spektakulære, hængende blå-lilla blomsterklaser i maj. Meget kraftig vækst – kræver solidt espalier. Kan tage 3-5 år inden første blomstring.",
    forestGardenLayer: "climber",
    source: "builtin",
  },
  {
    id: "humle",
    name: "Humle",
    latinName: "Humulus lupulus",
    category: "climber",
    family: "cannabaceae",
    lifecycle: "perennial",
    spacingCm: 100,
    rowSpacingCm: 150,
    light: "full-sun",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🍺",
    description: "Hurtigvoksende dansk klatreplante (op til 6-8 m/år). Humlekopper bruges til ølbrygning. Dør ned om vinteren og skyder igen om foråret.",
    forestGardenLayer: "climber",
    source: "builtin",
  },
  {
    id: "pibevin",
    name: "Pibevin (Aristolochia)",
    latinName: "Aristolochia macrophylla",
    category: "climber",
    family: "aristolochiaceae",
    lifecycle: "perennial",
    spacingCm: 100,
    rowSpacingCm: 150,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🍃",
    description: "Kraftig klatreplante med store, hjerteformede blade (op til 30 cm). Perfekt til at dække vægge og hegn. Helt hårdfør i Danmark.",
    forestGardenLayer: "climber",
    source: "builtin",
  },
  {
    id: "vildvin",
    name: "Vildvin",
    latinName: "Parthenocissus quinquefolia",
    category: "climber",
    family: "vitaceae",
    lifecycle: "perennial",
    spacingCm: 150,
    rowSpacingCm: 200,
    light: "full-sun",
    water: "low",
    soil: ["loamy", "sandy", "clay"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🍁",
    description: "Selvhæftende klatreplante med fantastisk rød høstfarve. Dækker hurtigt store vægflader. Helt hårdfør.",
    forestGardenLayer: "climber",
    source: "builtin",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // JORDFORBEDRERE (soil-amendment)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "komfrey",
    name: "Komfrey (Kulsukker)",
    latinName: "Symphytum × uplandicum",
    category: "soil-amendment",
    family: "boraginaceae",
    lifecycle: "perennial",
    spacingCm: 60,
    rowSpacingCm: 80,
    light: "partial-shade",
    water: "medium",
    soil: ["loamy", "clay"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🌱",
    description: "Dynamisk akkumulator – trækker næring op fra dyb jord. Blade bruges som mulch, kompost-aktivator eller flydende gødning.",
    forestGardenLayer: "herbaceous",
    source: "builtin",
  },
  {
    id: "lucerne",
    name: "Lucerne (Alfalfa)",
    latinName: "Medicago sativa",
    category: "soil-amendment",
    family: "fabaceae",
    lifecycle: "perennial",
    sowOutdoor: { from: 4, to: 8 },
    spacingCm: 0,
    light: "full-sun",
    water: "low",
    soil: ["sandy", "loamy"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🌿",
    description: "Dybtrodende bælgplante der fikserer kvælstof og løsner underjord. Fremragende grøngødning. Kan slås flere gange.",
    forestGardenLayer: "ground-cover",
    source: "builtin",
  },
  {
    id: "gul-sennep",
    name: "Gul Sennep",
    latinName: "Sinapis alba",
    category: "soil-amendment",
    family: "brassicaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 3, to: 9 },
    spacingCm: 0,
    light: "full-sun",
    water: "low",
    soil: ["any"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🌼",
    description: "Hurtigvoksende grøngødning. Undertrykker ukrudt, løsner jord og biofumigerer mod jordsvampe. Undgå før kål!",
    forestGardenLayer: "ground-cover",
    source: "builtin",
  },
  {
    id: "rug-groengoed",
    name: "Vinterrug (grøngødning)",
    latinName: "Secale cereale",
    category: "soil-amendment",
    family: "poaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 8, to: 10 },
    spacingCm: 0,
    light: "full-sun",
    water: "low",
    soil: ["any"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🌾",
    description: "Perfekt vinterdækafgrøde. Holder jorden levende og forhindrer næringsstofudvaskning. Fræses ned om foråret.",
    forestGardenLayer: "ground-cover",
    source: "builtin",
  },
  {
    id: "oelraeddike",
    name: "Olieræddike",
    latinName: "Raphanus sativus var. oleiformis",
    category: "soil-amendment",
    family: "brassicaceae",
    lifecycle: "annual",
    sowOutdoor: { from: 7, to: 9 },
    spacingCm: 0,
    light: "full-sun",
    water: "low",
    soil: ["clay", "loamy"],
    goodCompanions: [],
    badCompanions: [],
    icon: "🌱",
    description: "Kraftig pælerod der bryder tætte jordlag (op til 1,5 m dyb). Fryser ned om vinteren og efterlader luftige kanaler.",
    forestGardenLayer: "ground-cover",
    source: "builtin",
  },
];
